calculation_parameters:
  crest_method: gfn2
  electronic_temperature: 300.0
  n_threads: 1
  solvent: null
mopac_params:
  keywords: PM7 EF PRECISE GNORM=0.01 NOINTER GRAPHF VECTORS MMOK CYCLES=20000
programs:
  crest_path: crest
  mopac_path: MOPAC2016.exe
  openbabel_path: obabel
supabase:
  enabled: true
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dnZ1Z3VrdGxrdHdqd2hvcHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjgxOTMsImV4cCI6MjA2MjYwNDE5M30.XS6tT47gZtLpbUHHIoXcXinvoSywiHUeAxpSclEn4cA
  storage:
    enabled: true
    molecules_bucket: molecule-files
  url: https://iyvvuguktlktwjwhoppf.supabase.co
