calculation_parameters:
  n_threads: 4
  crest_method: gfn2
  electronic_temperature: 300.0
  solvent:
openbabel_path: C:\Program Files\OpenBabel-3.1.1
crest_path: C:\thermo_grimme\programs\crest
xtb_path: C:\thermo_grimme\programs\xtb